### ISSUE TITLE
Code doesn't run without adding table scripts. Maybe integrate flyway?

### ISSUE THREAD

**Issue by sherlockhoe90** [anelsahovic/Tic-Tac-Toe#1]
Can you integrate flyway with this, and add the sql queries in order to create pre-made demo tables with user and match info?
That way it may be easier for some of us to be able to run the program and test it out/learn.

**Comment by sherlockhoe90** [comment]
I might be able to implement it and make it working/ create a PR, but I don't have that much of an idea or time for trial-error guesswork n all.

**Comment by sherlockhoe90** [comment]
Nevermind, I'm just having trouble with making the db connection. I'll use the CRUD for that.

**Comment by anelsahovic** [comment]
Hello, I pushed the new branch of integrating the flyway but it has one error of finding the database for some reason. At the moment I am busy but I will try to resolve that issue as soon as posible.

**Comment by anelsahovic** [comment]
I Successfully integrated the flyway into the project . The problem was the version of flyway. If you have any other questions /suggestions feel free to reach out.
